# Generated by Django 6.0.4 on 2026-08-20 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0005_alter_enrollment_id_alter_paymentdetail_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('payment_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='enrollments.paymentdetail')),
            ],
            options={
                'ordering': ['-paid_at'],
            },
        ),
    ]
